[acoustics]
n_fft = 768
win_length = 768
sr = 24000
hop_length = 384


[inferencer]
path = "fullsubnet.inferencer.inferencer.Inferencer"
type = "full_band_crm_mask"
[inferencer.args]
n_neighbor = 23


[dataset]
path = "fullsubnet.dataset.dataset_inference.Dataset"
[dataset.args]
dataset_dir_list = [
    "data/DNS-Challenge/DNS-Challenge-interspeech2020-master/datasets/test_set/synthetic/no_reverb/"
]
sr = 24000


[model]
path = "fullsubnet.model.fullsubnet.Model"
[model.args]
sb_num_neighbors = 23
fb_num_neighbors = 0
num_freqs = 385
look_ahead = 2
sequence_model = "LSTM"
fb_output_activate_function = "ReLU"
sb_output_activate_function = false
fb_model_hidden_size = 512
sb_model_hidden_size = 384
weight_init = false
norm_type = "offline_laplace_norm"
num_groups_in_drop_band = 2

